language: python
python:
- '2.7'
install: pip install -r setup/requirements.txt
script: cd test; nosetests
before_install:
- openssl aes-256-cbc -K $encrypted_2931867a4314_key -iv $encrypted_2931867a4314_iv
  -in oauth_client.pkl.enc -out oauth_client.pkl -d
